<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>9af8006d-9d28-4a63-ad53-3d2b0a64c5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/ng-component/div/app-administrators-resolutions-table/form/div[2]/ngb-pagination/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f319ae6-24e8-46cf-9df5-80bb39e60a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link ng-star-inserted</value>
      <webElementGuid>9d4576c4-3280-4a7c-919b-0c163ae30251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2 </value>
      <webElementGuid>b6923ca9-44a6-488d-b179-b2b7bb74e2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/div[1]/app-administrators-resolutions-table[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;d-flex justify-content-between px-4 pt-3 ng-star-inserted&quot;]/ngb-pagination[1]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item ng-star-inserted&quot;]/a[@class=&quot;page-link ng-star-inserted&quot;]</value>
      <webElementGuid>9b4b971d-d0a9-4ed6-b2a1-3e7a80b5ab0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/ng-component/div/app-administrators-resolutions-table/form/div[2]/ngb-pagination/ul/li[3]/a</value>
      <webElementGuid>53cbaf1b-6359-4a0e-8e57-49b0c350268c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>0722296a-78d9-4ace-a930-186f43e96b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(current)'])[1]/following::a[1]</value>
      <webElementGuid>3743bd35-ba09-4be0-bcd4-fd62acb0e1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[5]/following::a[3]</value>
      <webElementGuid>1c54a98c-a3fa-40f1-926c-72f5d73f7535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/preceding::a[2]</value>
      <webElementGuid>6915be4e-5a6f-4bc7-a153-75cfe6c31af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>47491110-092f-4078-83b6-6a779cea1d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[19]</value>
      <webElementGuid>1229ccc4-ba83-414d-a872-ea36e8a15092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[3]/a</value>
      <webElementGuid>2ffa4429-66f9-48a9-ada7-e3727bff0d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' 2 ' or . = ' 2 ')]</value>
      <webElementGuid>8b29cc53-f698-48d6-8d44-8fdf427e8742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
