<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>37b4f117-8fe1-47ef-bbc9-e3931112d5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgotPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgotPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8508d883-600b-4c9c-98e8-974c0ebed73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotPassword</value>
      <webElementGuid>49a29136-fe83-40e0-a74e-c37ad5a6c0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gatsbytest.onmicrosoft.com/B2C_1A_Administrator_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=ci9ZSWNsdEhYWW12MFlzT0ViTzZWaEJSZUdYcEZhb012YSt4bnQ2eDdMQzNqMDVhNy9oaFFQdElIaVpKWjU2M3JOUDdxNEZLUDZWcDVTeVQweDloK1E9PTsyMDIzLTEwLTA0VDEzOjQyOjAyLjI3NTc2NTZaO1hVbkJaYzI3MXErcGQ4bGNYRG9PeUE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjo0fQ==&amp;tx=StateProperties=eyJUSUQiOiI5ZDMxMzZmMy1hYjhhLTQ4YmYtOWE4NS1jNzJjZGY0Zjg1YTIifQ&amp;p=B2C_1A_Administrator_SignUpSignIn</value>
      <webElementGuid>f0031946-0b5a-4c23-84fe-0c6340c23c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>08c0c302-a9d9-408d-a880-b259e01ebea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPassword&quot;)</value>
      <webElementGuid>02771936-0bc0-4770-a555-e6fb3c9434ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgotPassword']</value>
      <webElementGuid>4ce45086-3da9-4d94-b654-e097a8271cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div[2]/div/a</value>
      <webElementGuid>3cd39c67-ad13-491e-bc2d-74a034aa8dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>2ed942a4-bdef-4e9e-9893-9e0d27adea8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>fc2bf3bd-8184-4928-b407-43f21559f8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::a[1]</value>
      <webElementGuid>6f8136ac-efcf-4947-b880-860a7e43fdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>3a458ba6-d54c-44e0-9803-4d7091622c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>c088bd3f-9705-44a5-bd64-c607929390a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gatsbytest.onmicrosoft.com/B2C_1A_Administrator_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=ci9ZSWNsdEhYWW12MFlzT0ViTzZWaEJSZUdYcEZhb012YSt4bnQ2eDdMQzNqMDVhNy9oaFFQdElIaVpKWjU2M3JOUDdxNEZLUDZWcDVTeVQweDloK1E9PTsyMDIzLTEwLTA0VDEzOjQyOjAyLjI3NTc2NTZaO1hVbkJaYzI3MXErcGQ4bGNYRG9PeUE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjo0fQ==&amp;tx=StateProperties=eyJUSUQiOiI5ZDMxMzZmMy1hYjhhLTQ4YmYtOWE4NS1jNzJjZGY0Zjg1YTIifQ&amp;p=B2C_1A_Administrator_SignUpSignIn')]</value>
      <webElementGuid>73a52244-11ec-4ebc-a882-0712b5e4f74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>83a5ade0-7bf7-41ce-a008-f1b5e1844faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgotPassword' and @href = '/gatsbytest.onmicrosoft.com/B2C_1A_Administrator_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=ci9ZSWNsdEhYWW12MFlzT0ViTzZWaEJSZUdYcEZhb012YSt4bnQ2eDdMQzNqMDVhNy9oaFFQdElIaVpKWjU2M3JOUDdxNEZLUDZWcDVTeVQweDloK1E9PTsyMDIzLTEwLTA0VDEzOjQyOjAyLjI3NTc2NTZaO1hVbkJaYzI3MXErcGQ4bGNYRG9PeUE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjo0fQ==&amp;tx=StateProperties=eyJUSUQiOiI5ZDMxMzZmMy1hYjhhLTQ4YmYtOWE4NS1jNzJjZGY0Zjg1YTIifQ&amp;p=B2C_1A_Administrator_SignUpSignIn' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>3fd8eaa8-4f41-4461-aca7-e9f608e34ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
