<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_groupOperators</name>
   <tag></tag>
   <elementGuidId>c77ffbdc-4021-4311-954e-1ec44cd89dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navigation-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navigation-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5048f69d-a0f3-42aa-8ac7-5b0c8172850c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item d-flex flex-row</value>
      <webElementGuid>7e4f299a-6f46-4865-bd4d-d468671128b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navigation-6</value>
      <webElementGuid>3507d5a0-5783-456d-8a42-bc43f58fe307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administrators/operator</value>
      <webElementGuid>63740bea-2157-4f21-842d-8284e62fa869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>groupOperators</value>
      <webElementGuid>945b250f-b8a6-421e-97b4-d3786cfee2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-6&quot;)</value>
      <webElementGuid>63e60a74-e002-4667-bcdd-f08b210eb03b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navigation-6']</value>
      <webElementGuid>0cd6dfff-5e2a-4ed9-955c-fa6fe1d76d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-nav']/app-navigation/div/app-navigation-item[6]/a</value>
      <webElementGuid>f678e0cf-43ac-469a-8b86-e179480a1df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrators'])[1]/preceding::a[3]</value>
      <webElementGuid>9708fc52-cc35-4b0e-8143-2ab07c5664a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::a[4]</value>
      <webElementGuid>558a770a-325d-4b6b-8c20-67428f63602f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/administrators/operator')]</value>
      <webElementGuid>1daa3636-481e-4553-ad75-a34bd6dada5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-navigation-item[6]/a</value>
      <webElementGuid>e31c1ce5-fe50-44a0-b433-86890a48c4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navigation-6' and @href = '/administrators/operator' and (text() = 'groupOperators' or . = 'groupOperators')]</value>
      <webElementGuid>3c60c0ce-8efc-4a96-9229-a40057ca18be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
