<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Andrew1_1</name>
   <tag></tag>
   <elementGuidId>77309454-2ba2-4cb9-89ae-95950f159759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='actionDropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionDropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e70deb1-5f9c-433d-80a5-de32994e0132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionDropdown</value>
      <webElementGuid>501d1403-ef8b-428b-8c99-53728b68ba0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-outline-primary</value>
      <webElementGuid>cb6bf3df-a96a-418c-853a-58cae485adbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>70441d8f-fb0b-4688-9914-03e8d9b926b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andrew1</value>
      <webElementGuid>ae4015da-e941-4600-b918-15a2a7af5be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/app-administrators-driver[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;driver-bg d-flex justify-content-start mb-4 px-4&quot;]/div[@class=&quot;d-flex justify-content-between w-100&quot;]/div[@class=&quot;d-inline-block button-action dropdown&quot;]/button[@id=&quot;actionDropdown&quot;]</value>
      <webElementGuid>93c4b7fc-92e9-4a1e-8f23-b6a49344172e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='actionDropdown']</value>
      <webElementGuid>f40beecb-40e9-4f78-b2d5-e9ff3ab02485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-administrators-driver/div/div/div/button</value>
      <webElementGuid>50677828-84c4-4971-a958-ae1278edc00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[2]/following::button[1]</value>
      <webElementGuid>4076af6a-4ad9-45ba-af47-3a9d7fb2e2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::button[1]</value>
      <webElementGuid>b8391846-1c0a-4787-9659-53728f9bff9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Operator'])[1]/preceding::button[1]</value>
      <webElementGuid>fcac30f9-2997-43b1-9bf3-44ccb3a3471e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aaralyn'])[1]/preceding::button[4]</value>
      <webElementGuid>e1a27b43-034b-4d29-a292-73910cf674e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Andrew1']/parent::*</value>
      <webElementGuid>af82806a-9464-46d6-a49c-67314412009a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>57dbfb12-68d1-4cb0-aba8-caf9ad9bd100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'actionDropdown' and (text() = 'Andrew1' or . = 'Andrew1')]</value>
      <webElementGuid>1f6523b5-a8c3-42bd-8aab-25755d444af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
