<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Single</name>
   <tag></tag>
   <elementGuidId>2dd9a35f-94d3-474d-b433-e245a34f61fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/app-administrators-driver/div[2]/div[2]/app-administrators-driver-add-driver-dropdown/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>36ebe597-3d6b-4efd-91e1-4172a5a749b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>16bf361b-dd1f-4a8e-b040-36d60d028455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42435811-17ec-4c94-9554-e20d0889558a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Single</value>
      <webElementGuid>b1af4586-02b9-4fed-9aaf-bdf9de046d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/app-administrators-driver[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;driver-bg&quot;]/div[@class=&quot;px-4 pt-3 d-flex justify-content-end&quot;]/app-administrators-driver-add-driver-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-inline-block button-action pe-0 show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/button[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>6412ecef-e8aa-4a57-a52c-e472c6a9cb37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-administrators-driver/div[2]/div[2]/app-administrators-driver-add-driver-dropdown/div/div/button[2]</value>
      <webElementGuid>099bea71-4912-4ca5-b5a6-9aef393205fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multiple'])[1]/following::button[1]</value>
      <webElementGuid>979ef8b4-a536-4d15-a7ef-242358434137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Drivers'])[1]/following::button[2]</value>
      <webElementGuid>a7bddfb7-d3c2-490e-9035-ae37356040e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARCHIVE'])[1]/preceding::button[1]</value>
      <webElementGuid>b7ebc3a6-d9cc-4961-9d48-b5c882553f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REINSTATE'])[1]/preceding::button[2]</value>
      <webElementGuid>c4ab8b22-f6d3-4aeb-bd85-079415d6818f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Single']/parent::*</value>
      <webElementGuid>6ef2348d-ec03-4b2d-aa61-05a002b33ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5b6b77e5-f6a0-40bf-812f-299b81357764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Single' or . = 'Single')]</value>
      <webElementGuid>babb2d22-1c14-48a8-af6c-a6b22f8d3253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
