<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Engagement</name>
   <tag></tag>
   <elementGuidId>22ea2bf2-623c-4835-bf0a-b424d2a16269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.accordion-button.collapsed.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f65adf2-4cd1-4eaa-9160-b364bf6b49fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdf983af-232e-48af-b0d2-1fb8d4d9e771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button collapsed ng-star-inserted</value>
      <webElementGuid>ef9e14dc-8d99-4c75-93f2-1f89662bb50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab9eb3cd-1d81-4f72-9115-a8d7cf0b220c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sectionId-cebdaf16-f158-49fc-885a-d1d0ba2d3bca</value>
      <webElementGuid>6091de22-8406-4409-9d7e-21bb0eb11a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Engagement</value>
      <webElementGuid>dc5ad2dd-ed61-40b1-a507-c575885b90ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionId-cebdaf16-f158-49fc-885a-d1d0ba2d3bca-header&quot;)/button[@class=&quot;accordion-button collapsed ng-star-inserted&quot;]</value>
      <webElementGuid>37697689-f3f9-4eb8-905f-c22bd110abf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>a138aea1-d2ce-47a4-aee8-064477a24db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionId-cebdaf16-f158-49fc-885a-d1d0ba2d3bca-header']/button</value>
      <webElementGuid>a22cecff-5f11-4350-b422-ed6d73130e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/following::button[1]</value>
      <webElementGuid>bf8e1c8f-c619-428a-92de-517004995d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/following::button[2]</value>
      <webElementGuid>6bc4d07f-f5c2-4207-b155-4f5b584419a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Working Practices'])[1]/preceding::button[1]</value>
      <webElementGuid>ebed6008-2162-4817-a456-2e31fe258840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-accordion/div/div/button</value>
      <webElementGuid>598bf40f-f4eb-47a4-afe7-4ef0a0ac8681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  Engagement' or . = '  Engagement')]</value>
      <webElementGuid>48057c84-80d2-4cd5-8bbb-63efa25e0fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
