<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aug 31 operator</name>
   <tag></tag>
   <elementGuidId>dea8a7ec-e63b-4978-bc66-91ab99958b37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/app-administrators-driver/div/div/div/div/div[9]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07f546d6-62b7-4a98-b5d8-fbf69dfecdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>328d3c17-ed31-4471-aedc-9c0df70a8dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f2ac95f7-5056-4d64-8405-68e3e75df48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aug 31 operator</value>
      <webElementGuid>6b196e88-733e-4a5e-aa0b-36f2a39b6fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/app-administrators-driver[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;driver-bg d-flex justify-content-start mb-4 px-4&quot;]/div[@class=&quot;d-flex justify-content-between w-100&quot;]/div[@class=&quot;d-inline-block button-action show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/div[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>0a1e0e1b-1d55-4cc0-9a58-96012c9474e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-administrators-driver/div/div/div/div/div[9]/button</value>
      <webElementGuid>cb468018-0d21-46a4-bfe7-96085aac407d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ascar'])[1]/following::button[1]</value>
      <webElementGuid>b26da12e-977f-4a21-a58d-016cf663a515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple Taxis'])[1]/following::button[2]</value>
      <webElementGuid>684a1917-911d-4357-b512-6da3846b1bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bolt Taxi'])[1]/preceding::button[1]</value>
      <webElementGuid>91608eca-e067-4303-9efa-3abdb7bc6356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dan House'])[1]/preceding::button[2]</value>
      <webElementGuid>639a7882-e658-4c96-a68d-133d2bce28cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aug 31 operator']/parent::*</value>
      <webElementGuid>688c7eda-2c2e-4b6d-a9a7-8dc8691c1959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>68007e01-1571-4d4a-8964-ba32744f1c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Aug 31 operator' or . = 'Aug 31 operator')]</value>
      <webElementGuid>b44682cf-77a8-4f29-b75d-2adcb941af9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
