<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add DriversMultipleSingle</name>
   <tag></tag>
   <elementGuidId>0a2280e9-1025-4472-b6f4-5b04a483307a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/app-administrators-driver/div[2]/div[2]/app-administrators-driver-add-driver-dropdown/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-inline-block.button-action.pe-0.dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8dccedeb-24b6-4a85-a79e-6a6b87c746e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-inline-block button-action pe-0 dropdown</value>
      <webElementGuid>c48dcb03-06b2-45ed-8b05-534a7f993e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add DriversMultipleSingle</value>
      <webElementGuid>6eae6a08-4600-4713-b2a3-438f81f54082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/app-administrators-driver[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;driver-bg&quot;]/div[@class=&quot;px-4 pt-3 d-flex justify-content-end&quot;]/app-administrators-driver-add-driver-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-inline-block button-action pe-0 dropdown&quot;]</value>
      <webElementGuid>5acc2338-1f58-47ef-bcb8-19e2a751f9a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-administrators-driver/div[2]/div[2]/app-administrators-driver-add-driver-dropdown/div</value>
      <webElementGuid>c588bde9-d8cc-4090-b9b0-94d81c0d7206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yikes'])[1]/following::div[6]</value>
      <webElementGuid>2701a2f5-9308-45ba-8803-76e8eebfca9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yellow cabs'])[1]/following::div[7]</value>
      <webElementGuid>a28e3132-d7fb-4a0d-939d-0ea6265b0fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-administrators-driver-add-driver-dropdown/div</value>
      <webElementGuid>e5633168-db10-4edf-aa61-3311d56f2716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add DriversMultipleSingle' or . = 'Add DriversMultipleSingle')]</value>
      <webElementGuid>c55afae8-5e49-4235-a5fc-8fb5f6757752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
