<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e0400045-bda7-44e3-869f-866c44d26b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/app-administrators-operator/div/div/app-image-button-controlled/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1b386f2-188b-4a8e-998f-61b240cf4f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/icons/ic_add_circle.svg</value>
      <webElementGuid>2b515b92-5c37-4b8f-8826-6011a866e069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/app-administrators-operator[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;px-4 mt-5&quot;]/div[@class=&quot;mt-4 d-flex justify-content-end align-items-center&quot;]/app-image-button-controlled[@class=&quot;customCssClass 's-2&quot;]/button[1]/img[1]</value>
      <webElementGuid>07f229e8-4273-40c1-a970-8b02f0709f41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-administrators-operator/div/div/app-image-button-controlled/button/img</value>
      <webElementGuid>d4a4cc04-a84d-40e0-af7e-631fc0b862b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>14b5ebf1-5513-4daa-889d-c11ebcc3ee8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/icons/ic_add_circle.svg']</value>
      <webElementGuid>072856c7-a833-4e64-8d3e-699f1cc435ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>a6913c75-bd61-4125-b995-e55bc600ef35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/icons/ic_cancel.svg']</value>
      <webElementGuid>e870a089-2d4f-45c5-b06e-cb8d4c77a179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
