<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Primary Contact Email_mat-input-13</name>
   <tag></tag>
   <elementGuidId>6fd9676a-d534-4274-93e2-247063752e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-13']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-13</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9743faf-4f83-495b-bbcc-aebb05bca592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8da0494b-7a2b-4bc5-90d2-c09519cd8be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>primaryContactTelNumber</value>
      <webElementGuid>3ce6db1e-5757-4847-a28d-0fd0599a6f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c148-14 ng-untouched ng-invalid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>c435ec3e-ef7d-45af-8804-734b57ae7d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-13</value>
      <webElementGuid>841e8951-cd72-44e9-b71a-c39f9c1fd0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>289610e2-b416-4f3c-bdcb-8d9cce263eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>018af9d5-7947-4a43-9a56-1f1ce370b29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-13&quot;)</value>
      <webElementGuid>cce63f62-4b48-4bc6-8f3f-d84a7b59c1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-13']</value>
      <webElementGuid>a9f45f62-c581-41c7-98e9-59fb4b461858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-administrators-add-operator/div/div[2]/div/form/mat-form-field[14]/div/div/div[3]/input</value>
      <webElementGuid>6077643b-db5d-4d24-8468-745c80018914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[14]/div/div/div[3]/input</value>
      <webElementGuid>c07acf3d-5d7a-4825-b884-185f10344ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'mat-input-13']</value>
      <webElementGuid>c9253160-d59c-4047-abfa-d03b5de084a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
