<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ngb-highlight_SivaJ</name>
   <tag></tag>
   <elementGuidId>27e7fbc7-e82e-442c-9c77-cf8473dab990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/ng-component/div/app-administrators-resolutions-table/form/table/tbody/tr[25]/td/ngb-highlight</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ngb-highlight</value>
      <webElementGuid>e990eba9-fed2-4011-8e62-4e0f7b371f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SivaJ</value>
      <webElementGuid>7782669f-3c18-4cb7-ba29-e20c25ca7e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/div[1]/app-administrators-resolutions-table[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/table[@class=&quot;mat-sort&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;pointer ng-star-inserted&quot;]/td[1]/ngb-highlight[1]</value>
      <webElementGuid>0baa77b3-61d6-4d2c-b01a-e482b1a053c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/ng-component/div/app-administrators-resolutions-table/form/table/tbody/tr[25]/td/ngb-highlight</value>
      <webElementGuid>baed3545-fb4c-427d-b016-03f5dbc7af26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[4]/following::ngb-highlight[1]</value>
      <webElementGuid>2f3ae420-6923-462c-a5f6-ae6d4dd2c7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Russo Taxis'])[1]/following::ngb-highlight[1]</value>
      <webElementGuid>0c889b7b-1f8a-49a0-8a97-a1ac8eee2e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[7]/preceding::ngb-highlight[2]</value>
      <webElementGuid>cfa16001-723b-4559-bb57-19e7b532dbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SivaJ'])[2]/preceding::ngb-highlight[2]</value>
      <webElementGuid>12dbe8b8-cab2-4ae1-a49e-dde787f135c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SivaJ']/parent::*</value>
      <webElementGuid>35678805-9368-4577-a035-bc8abc676801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/ngb-highlight</value>
      <webElementGuid>7c15e213-963a-4488-947e-132cbf071316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ngb-highlight[(text() = 'SivaJ' or . = 'SivaJ')]</value>
      <webElementGuid>0abedeef-be60-4240-a8a8-57ca42db6f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
