<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Resolutions</name>
   <tag></tag>
   <elementGuidId>11841467-63b3-4bdf-8424-4a3582501a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navigation-2']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navigation-2 > p.menu-item-title.mt-auto.mb-auto.ms-0.me-0.ps-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ae77b98f-e708-4402-8b67-d9fdda4bdbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-title mt-auto mb-auto ms-0 me-0 ps-3</value>
      <webElementGuid>4b65b9bf-7a2b-4097-981a-308a66518a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resolutions</value>
      <webElementGuid>54f0ecc7-3500-42ad-b716-593cbb8e0f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-2&quot;)/p[@class=&quot;menu-item-title mt-auto mb-auto ms-0 me-0 ps-3&quot;]</value>
      <webElementGuid>9dab3713-94e3-4a82-bfcb-30aafa3f2ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navigation-2']/p</value>
      <webElementGuid>51abeb0b-5009-4b17-ac5b-cb50c6b74e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrators'])[1]/preceding::p[11]</value>
      <webElementGuid>7f423d4d-a75c-4d99-acab-fb505c2375fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::p[11]</value>
      <webElementGuid>773ad53e-8c00-43a4-bbbb-adb35c8bba5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resolutions']/parent::*</value>
      <webElementGuid>1bc42f1b-f670-423a-9e6b-310dbd67abe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-navigation-item[2]/a/p</value>
      <webElementGuid>1400de2d-1416-4e1e-a377-de9f247a2f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Resolutions' or . = 'Resolutions')]</value>
      <webElementGuid>edaacd4a-014f-46f7-a6b6-25815e5ffff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
