<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_29092023 1148</name>
   <tag></tag>
   <elementGuidId>3bcad220-8172-4761-9cc1-e869dcba081f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/ng-component/div[2]/table/tbody/tr[6]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>26f497af-eaa3-4751-aa85-65f13f0d3f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>21591733-af53-4915-a251-98a2cfd2d688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 29/09/2023 11:48 </value>
      <webElementGuid>2e3af27a-dbc5-494c-8499-e69bb770e30d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/table[@class=&quot;mat-sort&quot;]/tbody[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;pointer ng-star-inserted&quot;]/td[@class=&quot;pointer&quot;]</value>
      <webElementGuid>dc3c1ece-66e9-4ee6-9d72-4f6bd2510519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/ng-component/div[2]/table/tbody/tr[6]/td[2]</value>
      <webElementGuid>f25b6ae7-3ed9-45ec-91f8-bfee1d178bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siva Sankari'])[1]/following::td[1]</value>
      <webElementGuid>5d3a8abb-bce1-4db8-82d1-ee45636e7fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andrew1'])[1]/following::td[3]</value>
      <webElementGuid>56445efc-fd9b-484b-97cd-6af62b00134f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driver'])[5]/preceding::td[1]</value>
      <webElementGuid>0707ecd6-1cd9-4d7d-88e5-fde12c52d316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aug 31 operator'])[1]/preceding::td[2]</value>
      <webElementGuid>6ae4e9ad-434a-4980-a502-ace447a6ec5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='29/09/2023 11:48']/parent::*</value>
      <webElementGuid>10912f54-b592-4bcd-8e8b-269f9c1aba62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]</value>
      <webElementGuid>022854fb-33a9-4672-bd06-7f51afbd0fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' 29/09/2023 11:48 ' or . = ' 29/09/2023 11:48 ')]</value>
      <webElementGuid>20d1776a-b3d7-439d-a424-61802fe29e4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
