<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Your query_form-control</name>
   <tag></tag>
   <elementGuidId>bc9b0ef9-3589-445f-ac59-32397b38d26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sectionId-cebdaf16-f158-49fc-885a-d1d0ba2d3bca']/div/div[2]/div[3]/div/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7b13b709-c3e3-46e4-8f9d-a7ab25e4cc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b1ed0ed6-01b9-406c-a884-5c2e7e094f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a193880-e16a-4903-9e63-7f5bde9e43e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sectionId-cebdaf16-f158-49fc-885a-d1d0ba2d3bca&quot;)/div[@class=&quot;accordion-body&quot;]/div[@class=&quot;border-top py-4 px-5 ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ms-5 my-4 ng-star-inserted&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;mb-4 col-sm-7 col-12 accordion-assessment-query&quot;]/textarea[@class=&quot;form-control&quot;]</value>
      <webElementGuid>12a472b0-f7a0-4b52-9c14-42d67cb59efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sectionId-cebdaf16-f158-49fc-885a-d1d0ba2d3bca']/div/div[2]/div[3]/div/div/div/textarea</value>
      <webElementGuid>54f0cad0-f185-42e1-a1ad-e1aaa50d288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>befc2a97-5635-49e5-8c6c-531159ec3e0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
