<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drivers</name>
   <tag></tag>
   <elementGuidId>6ec09eaa-e361-4692-b218-780106324339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/ng-component/div/div/app-shared-back-button/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.heading-back.pointer.d-flex.align-items-center.ps-1 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df670c8e-d3b5-4e3e-8f03-f30940135988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drivers</value>
      <webElementGuid>763b0563-4b28-482a-bffe-637d22ca8b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;px-3 pb-3 pt-0&quot;]/app-shared-back-button[1]/div[@class=&quot;heading-back pointer d-flex align-items-center ps-1&quot;]/div[1]</value>
      <webElementGuid>6de26f0a-6cdf-4ec0-b4cd-8ba6b0b96dff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/ng-component/div/div/app-shared-back-button/div/div</value>
      <webElementGuid>51342f1c-050f-4b1e-b124-e6aa141c204c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[3]/following::div[7]</value>
      <webElementGuid>7ec75f01-1bb4-4a56-8616-78c88a8b2950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Guide'])[1]/following::div[7]</value>
      <webElementGuid>6de0b51a-8743-4084-8ee8-1037fd7ffc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sivasankari Selvam sept 2'])[1]/preceding::div[3]</value>
      <webElementGuid>cd7425f1-1791-4a2f-b7c5-b0002461c956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='driver'])[1]/preceding::div[3]</value>
      <webElementGuid>506f989f-c99f-498f-b64a-e6a18f4c0579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-shared-back-button/div/div</value>
      <webElementGuid>aadfcccd-9254-4e6f-8c48-b01596a28583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drivers' or . = 'Drivers')]</value>
      <webElementGuid>cb2a1783-57b2-4f75-b027-3f1854cf9b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
