<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_4 Blackburnes Mews, London, W1K 2LG</name>
   <tag></tag>
   <elementGuidId>773350dc-6fff-42bd-bf0f-e11d49d3e870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-290']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e77a1db3-e95c-482a-a249-4592b9ef0070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>627c2d8b-3017-4e5f-a4f7-02fa11fe0c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 4 Blackburnes Mews, London, W1K 2LG </value>
      <webElementGuid>d8c4b760-884e-411c-8a42-fa87112e4d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-290&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>f3cb58da-b3f9-450e-8bdf-717ce977a439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-290']/span</value>
      <webElementGuid>7b841e54-655a-4271-a040-e349aa66e5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-option-290', '&quot;', ')/span[@class=', '&quot;', 'mat-option-text', '&quot;', ']')])[1]/following::span[1]</value>
      <webElementGuid>e311c5df-2fc3-4fce-b79a-8d00da5f6a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::span[1]</value>
      <webElementGuid>47886fd4-8666-43aa-ad0e-8070df6f4897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ashaa Ltd, 8 Blackburnes Mews, London, W1K 2LG'])[1]/preceding::span[3]</value>
      <webElementGuid>ed8b357d-d283-4328-bf4f-b8289c23aab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat A, 8 Blackburnes Mews, London, W1K 2LG'])[1]/preceding::span[4]</value>
      <webElementGuid>2d675f9e-f123-4f03-98af-6e6023476588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4 Blackburnes Mews, London, W1K 2LG']/parent::*</value>
      <webElementGuid>2953ba0d-f22a-49e5-80de-a41f66b6f38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>c3276d7e-a1b2-4c26-90b4-5b62144c9676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 4 Blackburnes Mews, London, W1K 2LG ' or . = ' 4 Blackburnes Mews, London, W1K 2LG ')]</value>
      <webElementGuid>cf548d3c-efde-4e28-9247-e9c073fadc35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
