<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send verification code</name>
   <tag></tag>
   <elementGuidId>d16e8106-8bac-4636-8e08-4414732ac129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_ver_but_send</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='email_ver_but_send']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12242bcf-b7bb-4842-a9e1-576fb6186eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendButton</value>
      <webElementGuid>622a760a-0a38-4f39-ac5a-e1a07c9ec58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_ver_but_send</value>
      <webElementGuid>d2ec80ca-0d16-4363-90e7-3569a82e9277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfdb0164-3805-43b8-b820-8be34fe90f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Send verification code</value>
      <webElementGuid>a3d5f123-1fd6-414e-9d10-3a49597f3cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc6af586-89c5-40e2-90a8-21bafa5565a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send verification code</value>
      <webElementGuid>22de9b7e-dc90-4276-bece-7f956effe38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_ver_but_send&quot;)</value>
      <webElementGuid>0c6b5421-dd5d-4cae-ac5f-ff67bb220358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='email_ver_but_send']</value>
      <webElementGuid>c45f6e40-16da-4919-8f95-fcb6b743528a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attributeList']/ul/li/div/div[3]/button</value>
      <webElementGuid>4d45acf9-7d06-40d0-a37b-97e8c5492682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is this?'])[1]/following::button[1]</value>
      <webElementGuid>a52db9e9-a812-43ba-8d6b-9d59a7bb51ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send verification code to your email.'])[1]/following::button[1]</value>
      <webElementGuid>00c6beb3-76e0-4423-a762-ffb41f950892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/preceding::button[4]</value>
      <webElementGuid>103910d0-ac5e-425b-8a93-83ba2b8df18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[5]</value>
      <webElementGuid>44f7abc7-1690-46c9-b67b-b49404b79cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send verification code']/parent::*</value>
      <webElementGuid>215d7427-03fc-45af-bc7c-5b8ae6b51d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>15b6084d-3998-4875-8842-ac48edd64376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'email_ver_but_send' and @type = 'button' and (text() = 'Send verification code' or . = 'Send verification code')]</value>
      <webElementGuid>e8307ac7-4efe-4f4f-95e3-1b8ce89902bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
