<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dashboard</name>
   <tag></tag>
   <elementGuidId>e3af3496-142d-41c8-9c08-6a45003dc59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navLeft_Dashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navLeft_Dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eba0692d-a398-466c-9cc5-3083486e4e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>006e8ab2-e6f6-472e-aa8c-b444de0babe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>space-between center</value>
      <webElementGuid>36c99985-d093-4b1a-b4fb-4f3da845a312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-line</value>
      <webElementGuid>2c813152-48b5-4ec7-8ab2-daa1ea186caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navLeft_Dashboard</value>
      <webElementGuid>f705af16-3075-4a47-8f1e-d24bad8acd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dashboard </value>
      <webElementGuid>e8c204f1-988b-46b2-85ff-25a888fdb4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navLeft_Dashboard&quot;)</value>
      <webElementGuid>6f2aafc2-1d35-4b2a-b3b8-6efe153f6640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navLeft_Dashboard']</value>
      <webElementGuid>ed0d4f2f-2950-4c93-a895-b889e0c21419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-list-item[@id='module_left_navigation_71']/span/span[2]/a</value>
      <webElementGuid>080ba64a-a008-4281-b0c6-94cb05051d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dashboard')]</value>
      <webElementGuid>4506187b-befb-410c-b87f-9346cd4aedd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supply Chain Assurance'])[2]/following::a[1]</value>
      <webElementGuid>52d3cd74-8022-4255-be3f-8b098f237ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Manager'])[1]/following::a[1]</value>
      <webElementGuid>cd665451-730b-4cfb-a446-47b62c9eb37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>d0cf7ee3-f74d-47a2-8011-6e1bf4954065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contractors'])[1]/preceding::a[2]</value>
      <webElementGuid>220a203c-51b7-4632-8163-20c7a7d2ed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>8738ce59-29c0-421d-ac3a-6948e956e6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-list-item/span/span[2]/a</value>
      <webElementGuid>a2da5bac-30eb-4c25-9e10-3885ac2192f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navLeft_Dashboard' and (text() = ' Dashboard ' or . = ' Dashboard ')]</value>
      <webElementGuid>1b614b16-a1cf-49ea-89b7-4a7ebc0cc97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
