<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>1a5a4566-c4e6-4d6c-a866-5ea340100a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.forgot-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerColour']/div[2]/div/form/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a83ddccc-f36c-4399-a544-b623aabed406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>forgot-password</value>
      <webElementGuid>671fa68a-69b1-40ef-8556-9333c82d9b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/forgot-password</value>
      <webElementGuid>5872f01c-52ee-4249-bba8-8c6eb823cf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Forgot your password? </value>
      <webElementGuid>ad593576-2ff0-46fb-97a9-f687ef3a610c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerColour&quot;)/div[2]/div[@class=&quot;content&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;forgotten-password-container&quot;]/div[1]/a[@class=&quot;forgot-password&quot;]</value>
      <webElementGuid>e6187576-8ca3-48a0-94fb-35522791e250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerColour']/div[2]/div/form/div/div/a</value>
      <webElementGuid>3b9c6493-3ba6-4ed1-ba25-16c9e4cb97e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>e6027f57-4ac8-4711-bd0c-38057946d528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>4d91b5ad-4bb9-40a8-9a69-efac2b43cfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOG IN'])[1]/preceding::a[1]</value>
      <webElementGuid>ce11bb23-b038-4c8a-a5e6-439d8a0c964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(v.1.0.10141)'])[1]/preceding::a[1]</value>
      <webElementGuid>c88b0f6b-27d8-4d5a-af22-5156952a532e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>19313f7b-3bfd-453b-85b0-38e09108430c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/forgot-password')]</value>
      <webElementGuid>cea5728e-7cd6-4dea-ad1d-70ee69dab6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>03b2eb6e-b4c4-43f6-b46d-1dcd28be3f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/forgot-password' and (text() = ' Forgot your password? ' or . = ' Forgot your password? ')]</value>
      <webElementGuid>190a82c6-6a7f-4c36-b819-904bdeb53935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
