<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Indigo Contract Remittances</name>
   <tag></tag>
   <elementGuidId>84724826-52d2-43a3-8cc0-1c8a04b6aabf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navLeft_IndigoContractRemittances</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navLeft_IndigoContractRemittances']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>845cd88f-5825-4873-bb1d-342c319aeb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>7ec44b8f-af73-4014-ba96-0e8a976f0c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>space-between center</value>
      <webElementGuid>12e082d9-bd5e-4e45-bea9-f5433f83a2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-line</value>
      <webElementGuid>6abd5687-5d25-4bb9-a953-f194913f6adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navLeft_IndigoContractRemittances</value>
      <webElementGuid>fa79ec3c-8823-4367-9030-6b39435179a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Indigo Contract Remittances </value>
      <webElementGuid>63de6a1f-a8f6-4473-853c-e4d81694d55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navLeft_IndigoContractRemittances&quot;)</value>
      <webElementGuid>d51a8b8f-f3f0-4a20-8a58-24d158c29d37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navLeft_IndigoContractRemittances']</value>
      <webElementGuid>b17d5231-d9b0-42aa-b64e-be9a5425eaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-list-item[@id='module_left_navigation_60']/span/span[2]/a</value>
      <webElementGuid>3edd77f5-9482-4334-a24f-d14a9ea1dd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Indigo Contract Remittances')]</value>
      <webElementGuid>9e88d01a-db9f-4256-a6c9-78d2e82053e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrations'])[1]/following::a[1]</value>
      <webElementGuid>1cd15cfd-b2d5-4d9c-a63d-1025b1d54f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homepage'])[1]/following::a[2]</value>
      <webElementGuid>ce0dd38f-ba32-4095-a521-55cb43885f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indigo Invoices'])[1]/preceding::a[1]</value>
      <webElementGuid>cbae9a44-66f4-4f14-82ff-522acb350627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indigo Contractor List'])[1]/preceding::a[2]</value>
      <webElementGuid>328a6a15-098d-4403-91dd-6ad47522fa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indigo Contract Remittances']/parent::*</value>
      <webElementGuid>4e498326-1510-4ea0-8d89-699c4b315607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-list-item/span/span[2]/a</value>
      <webElementGuid>77e11a24-21fb-4791-8da7-f62e20ad161e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'navLeft_IndigoContractRemittances' and (text() = ' Indigo Contract Remittances ' or . = ' Indigo Contract Remittances ')]</value>
      <webElementGuid>ed129e73-30a0-47e2-88cd-20f2fe165170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
