<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_swap_horizIndigo Group</name>
   <tag></tag>
   <elementGuidId>f5abce42-d4b3-443d-a182-786361ae3d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.organisation-option.button-class-background-hover-10.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ab38241-4ea0-4781-92de-d880c74a0060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>fb656abb-7dea-493a-ac33-f5bf39f44363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutgap</name>
      <type>Main</type>
      <value>10px</value>
      <webElementGuid>b4cfe3d6-16b1-4ed3-924d-531511be9d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>start center</value>
      <webElementGuid>31261c30-f85c-4ec5-856d-5373a2504f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>organisation-option button-class-background-hover-10 ng-star-inserted</value>
      <webElementGuid>5a69715f-fed5-47a1-9822-7ebb7c432aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>swap_horizIndigo Group</value>
      <webElementGuid>b544733f-cf3a-4742-9225-d22cc818372f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerColour&quot;)/div[2]/div[@class=&quot;content&quot;]/app-homepage-header[1]/app-organisation-select[1]/div[@id=&quot;organisation-select&quot;]/div[@class=&quot;menu ng-star-inserted&quot;]/div[@class=&quot;organisation-container ng-star-inserted&quot;]/virtual-scroller[@class=&quot;vertical selfScroll&quot;]/div[@class=&quot;scrollable-content&quot;]/div[@class=&quot;organisation-option button-class-background-hover-10 ng-star-inserted&quot;]</value>
      <webElementGuid>e3a5d42b-8876-4567-9cd2-9f33ef296118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div</value>
      <webElementGuid>0818351d-271b-43ce-b4d6-991170a5a1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Profiles'])[1]/following::div[8]</value>
      <webElementGuid>ebb5eae4-d8c8-424b-8063-442724452f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£ test 06831370 212123133.'])[1]/following::div[23]</value>
      <webElementGuid>3e4b82f6-f500-4a6f-99c8-c04d1da7311b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sole Indigo Group'])[1]/preceding::div[2]</value>
      <webElementGuid>c70da334-9c19-4bde-be34-8984ca782d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//virtual-scroller/div[2]/div</value>
      <webElementGuid>82a8b4d6-c444-4a45-ae1a-abea34ab0987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'swap_horizIndigo Group' or . = 'swap_horizIndigo Group')]</value>
      <webElementGuid>5c40f24a-20cf-46e4-9c82-72e9403c8ba4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
