<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Marquee Contracting Limited</name>
   <tag></tag>
   <elementGuidId>e2b5d35c-7bd4-45be-b6ee-98b519064cdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.organisation-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2664e7b3-8206-4c20-8882-516b19bf4b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>organisation-option-text</value>
      <webElementGuid>c03574a7-dd34-4ffa-8947-77b84dd71a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marquee Contracting Limited</value>
      <webElementGuid>8f6d57da-ffea-401f-ae31-c6a94bad2f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerColour&quot;)/div[2]/div[@class=&quot;content&quot;]/app-homepage-header[1]/app-organisation-select[1]/div[@id=&quot;organisation-select&quot;]/div[@class=&quot;menu ng-star-inserted&quot;]/div[@class=&quot;organisation-container ng-star-inserted&quot;]/virtual-scroller[@class=&quot;vertical selfScroll&quot;]/div[@class=&quot;scrollable-content&quot;]/div[@class=&quot;organisation-option button-class-background-hover-10 ng-star-inserted&quot;]/div[@class=&quot;organisation-option-text&quot;]</value>
      <webElementGuid>6511ba09-c1b4-4e20-978a-e6263c39f9f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div/div</value>
      <webElementGuid>7e9169bb-c50a-4878-955c-4779ddde0564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Profiles'])[1]/following::div[9]</value>
      <webElementGuid>b7b7fc8c-fd3c-4b83-be69-1ccd849a1121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£ test 06831370 212123133.'])[1]/following::div[24]</value>
      <webElementGuid>70f7417e-3f8e-4936-af1f-a5c058df55b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help'])[1]/preceding::div[1]</value>
      <webElementGuid>c432f540-e414-4c2f-b2d4-cdeeef5914f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::div[2]</value>
      <webElementGuid>33779af9-8e9f-4dbe-b7de-23de070f9ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marquee Contracting Limited']/parent::*</value>
      <webElementGuid>dca9f70b-87a0-45c8-8fea-06b89b1277a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//virtual-scroller/div[2]/div/div</value>
      <webElementGuid>3d6dd660-4bcb-46fa-8003-59a33a9b656c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Marquee Contracting Limited' or . = 'Marquee Contracting Limited')]</value>
      <webElementGuid>64e1207e-9353-41a2-9f84-ae1920bf984e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
