<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We use cookies on our website. You are _364319</name>
   <tag></tag>
   <elementGuidId>c1a029a1-4e28-4455-a682-223870fd3ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50006f8d-ac4e-4986-a29a-e690a6cba3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>ef9636ab-3b98-4d09-8f8c-490385fe4d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>e1e1e33d-2b32-4f6b-b93b-ffd806982fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>cookieconsent</value>
      <webElementGuid>b0c263ed-4495-4ae7-8bfe-e844cc26399f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cookieconsent:desc</value>
      <webElementGuid>9985bf9d-5d45-47ad-9ed1-a382066263e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cc-window cc-banner cc-type-info cc-theme-classic cc-bottom cc-color-override-1151466599 </value>
      <webElementGuid>13b4d594-d6ae-4e2b-afea-5ff1c41e8e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We use cookies on our website. You are free to manage this via your browser setting at any time. To learn more about how we use them, please see our Cookie Policy.Continue</value>
      <webElementGuid>6f43954c-ca5b-4006-873e-d0e2131fddaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;platform-default-primary platform-default-primary-sidenav platform-default-primary-titles platform-default-primary-buttons&quot;]/div[@class=&quot;cc-window cc-banner cc-type-info cc-theme-classic cc-bottom cc-color-override-1151466599&quot;]</value>
      <webElementGuid>dce9829e-059b-4abd-b412-9267e97113dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>2d2f36cf-d189-4b0d-bd59-01ca6295a577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'We use cookies on our website. You are free to manage this via your browser setting at any time. To learn more about how we use them, please see our Cookie Policy.Continue' or . = 'We use cookies on our website. You are free to manage this via your browser setting at any time. To learn more about how we use them, please see our Cookie Policy.Continue')]</value>
      <webElementGuid>46f30aef-e9a5-4cb8-9ecf-b06b43f77f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
