<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Indigo Group</name>
   <tag></tag>
   <elementGuidId>58e5bf3f-9a34-43f4-8314-147c841f8cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.organisation-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07310107-ef3b-496d-93b9-d50a18a7a0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>organisation-option-text</value>
      <webElementGuid>12ef9068-542b-48fb-afb3-11b148f751f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indigo Group</value>
      <webElementGuid>6b993771-7882-4856-af5e-e777b08afe9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organisation-select&quot;)/div[@class=&quot;menu ng-star-inserted&quot;]/div[@class=&quot;organisation-container ng-star-inserted&quot;]/virtual-scroller[@class=&quot;vertical selfScroll&quot;]/div[@class=&quot;scrollable-content&quot;]/div[@class=&quot;organisation-option button-class-background-hover-10 ng-star-inserted&quot;]/div[@class=&quot;organisation-option-text&quot;]</value>
      <webElementGuid>e08b5114-7be6-4ea8-9341-6a5d301f66ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div/div</value>
      <webElementGuid>ae26585e-9fb2-4a9b-82c2-04eb02823f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Profiles'])[1]/following::div[9]</value>
      <webElementGuid>636f17bd-d553-4f23-80ad-9d80df8fe095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£ test 06831370 212123133.'])[1]/following::div[24]</value>
      <webElementGuid>bc6d0d15-6519-4117-92ff-17ef0d22de7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sole Indigo Group'])[1]/preceding::div[1]</value>
      <webElementGuid>47d15a9e-3018-43f9-b26a-4874aec3cf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help'])[1]/preceding::div[3]</value>
      <webElementGuid>8bed300d-02db-4749-9fce-030b9f70f1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indigo Group']/parent::*</value>
      <webElementGuid>9ddcc685-05ee-43cc-ac75-4703317cdf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//virtual-scroller/div[2]/div/div</value>
      <webElementGuid>e5b11203-427b-484b-971d-ad0ba063978e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Indigo Group' or . = 'Indigo Group')]</value>
      <webElementGuid>0ff28595-f356-4f7a-9bd8-a357bc0e87ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
