<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue_mat-drawer-backdrop ng-star-in_87a839</name>
   <tag></tag>
   <elementGuidId>42ab8a83-5779-4c3a-a52e-cf1fffa06aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.background.image-background</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='authentication-container']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b841155-7513-4d8a-9404-05144b0f45d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>background image-background</value>
      <webElementGuid>3ca43280-e2f4-4c8d-b6d7-0b463c5bf20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authentication-container&quot;)/div[@class=&quot;background image-background&quot;]</value>
      <webElementGuid>4368c2a3-968d-4965-ab00-8560ce1e882a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authentication-container']/div[2]</value>
      <webElementGuid>2db7751b-ac8b-4468-94f6-5411226bb34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-authentication-container/div/div[2]</value>
      <webElementGuid>fdf5885d-3b81-4b5a-8f2b-427123fd1cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-sidenav-container/div</value>
      <webElementGuid>d9eeddb8-42e8-4c2a-8a08-7e293778246c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
