<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Marquee Operations Limited</name>
   <tag></tag>
   <elementGuidId>e6c609c7-db73-43bf-a136-79ccfcb3449c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.organisation-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>921ac02f-7701-4eb3-ae56-24517771da56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>organisation-option-text</value>
      <webElementGuid>6eac1afe-196d-4d08-a232-e0b87ff6eb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marquee Operations Limited</value>
      <webElementGuid>32a0198c-d903-4272-9ebb-2944f8a93606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerColour&quot;)/div[2]/div[@class=&quot;content&quot;]/app-homepage-header[1]/app-organisation-select[1]/div[@id=&quot;organisation-select&quot;]/div[@class=&quot;menu ng-star-inserted&quot;]/div[@class=&quot;organisation-container ng-star-inserted&quot;]/virtual-scroller[@class=&quot;vertical selfScroll&quot;]/div[@class=&quot;scrollable-content&quot;]/div[@class=&quot;organisation-option button-class-background-hover-10 ng-star-inserted&quot;]/div[@class=&quot;organisation-option-text&quot;]</value>
      <webElementGuid>e9049f7e-7c17-4340-ad62-740fd61d7a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organisation-select']/div/div[2]/virtual-scroller/div[2]/div/div</value>
      <webElementGuid>bd692d43-e54d-4a94-8d2b-c4ebc0c15fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Profiles'])[1]/following::div[9]</value>
      <webElementGuid>4a5d8d17-339e-4a56-954e-024a71020b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£ test 06831370 212123133.'])[1]/following::div[24]</value>
      <webElementGuid>a43453f4-7dd5-4a10-986a-acaeefee1ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Marquee Operations Ltd'])[1]/preceding::div[1]</value>
      <webElementGuid>ea595ea8-3fc3-417d-9d13-d9987dadc173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need Help'])[1]/preceding::div[3]</value>
      <webElementGuid>a2450e84-5c96-4b9e-8edc-bcf1fedd244f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marquee Operations Limited']/parent::*</value>
      <webElementGuid>561d88ee-ee12-4bdf-88cc-78e7882fcd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//virtual-scroller/div[2]/div/div</value>
      <webElementGuid>726b90b9-4303-4968-8e90-3d21c66a09ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Marquee Operations Limited' or . = 'Marquee Operations Limited')]</value>
      <webElementGuid>7950a050-6845-4cea-8922-f19be9556a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
