<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>716c7cf5-e35b-4914-a3f8-462932b8d0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerColour']/div[2]/div/div/app-homepage-service-list/div/div/div/div[2]/div/div/div/app-homepage-process-card/mat-card/mat-card-content/div[2]/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.icon > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bae5d97c-2fcd-43e4-9f61-58a82d573128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://groupservicestest.blob.core.windows.net/accreditation-badges/ef31a44b-08e9-486f-b048-439187b43960-not-started</value>
      <webElementGuid>1ffd60c7-a9fe-46fc-9207-9fd65278996d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerColour&quot;)/div[2]/div[@class=&quot;content&quot;]/div[@class=&quot;content-wrapper body-content&quot;]/app-homepage-service-list[@class=&quot;homepage-service&quot;]/div[@class=&quot;service-container&quot;]/div[@class=&quot;service-flex&quot;]/div[@class=&quot;section-container&quot;]/div[2]/div[@class=&quot;list-container ng-star-inserted&quot;]/div[@class=&quot;lists&quot;]/div[@class=&quot;listScroll&quot;]/app-homepage-process-card[@class=&quot;cards ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator homepage-process-card blue&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;separator&quot;]/div[@class=&quot;icon&quot;]/img[1]</value>
      <webElementGuid>aec28ffc-6d93-4258-bf37-ea13f9fc9c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerColour']/div[2]/div/div/app-homepage-service-list/div/div/div/div[2]/div/div/div/app-homepage-process-card/mat-card/mat-card-content/div[2]/div[2]/div/img</value>
      <webElementGuid>0f8ecd99-51b4-4d85-9861-81c1d16a5540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://groupservicestest.blob.core.windows.net/accreditation-badges/ef31a44b-08e9-486f-b048-439187b43960-not-started')]</value>
      <webElementGuid>a90d45b0-20dc-4aab-b08a-9da7e4ee7ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>2b2b043d-d69e-42c0-8fb1-f41e4740dab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://groupservicestest.blob.core.windows.net/accreditation-badges/ef31a44b-08e9-486f-b048-439187b43960-not-started']</value>
      <webElementGuid>ccc95e09-9994-4649-9c89-ad94cf8dc740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='select-individual-button']/img)[2]</value>
      <webElementGuid>8fa01ac9-5e9e-4c1e-8293-cd3993169e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select-option-button[2]/div/img</value>
      <webElementGuid>3c5c2385-b3ab-4dd9-a421-66dbb3d96c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/icons/individual.svg']</value>
      <webElementGuid>bb333ef4-3b1b-4e18-aefd-ab96de5ff7c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
