<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Acl Client Portal_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>4554925d-88ab-41b5-8450-40a2b7c276b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#homepage_icon_70 > img.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homepage_icon_70']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3774d008-0e2e-4ae6-955b-f43bd1d55ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/hub/navigation/services/supply-chain.svg</value>
      <webElementGuid>7e4acf64-292e-4584-b54e-24e71f5ca818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>32e4ff69-1816-448b-afd5-d1e45b8ff9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homepage_icon_70&quot;)/img[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>223baa2a-827e-433a-87fb-af615ad0f225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homepage_icon_70']/img</value>
      <webElementGuid>832e8591-217c-4274-807e-0c256fd41e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/img</value>
      <webElementGuid>1b8b1b4b-5046-4f11-8eef-4c6a3fc15824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/hub/navigation/services/supply-chain.svg']</value>
      <webElementGuid>b544477c-e577-4948-a7d7-2a9be379694c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
