<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recover your password_field-forgot-pa_2710a4</name>
   <tag></tag>
   <elementGuidId>96588b20-d158-4a8c-8491-cdd216de1a9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-forgot-password-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-forgot-password-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>160ebf84-509c-4e0f-86e3-d28ce99d3207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a5dc7fa6-8af1-4572-ac7c-87cde66d230c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>49a40315-cdbf-49a5-a878-8b25e41b8a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-forgot-password-email</value>
      <webElementGuid>e9c5300c-fd51-4703-8bfc-155d0ed1a738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c113-3 ng-untouched ng-invalid cdk-text-field-autofill-monitored ng-dirty</value>
      <webElementGuid>1ca97e85-0c83-43cd-9a55-afa44ed613c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d4b0753-2c3a-47ea-a1f5-b5a73d77f311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22fe6b14-1b00-423b-9fcc-b6bafd49dbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-forgot-password-email&quot;)</value>
      <webElementGuid>17a0e7b4-dc22-49a3-8751-58ad73d4bc22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-forgot-password-email']</value>
      <webElementGuid>f0792c23-e3c0-4812-bf65-62e8d117ae80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerColour']/div[2]/div/form/mat-form-field/div/div/div[3]/input</value>
      <webElementGuid>6f87baac-1df3-410f-b027-81dd3603cc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6bfd0dd4-59a3-4e40-9a5d-37421e7014b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'field-forgot-password-email']</value>
      <webElementGuid>cd8ee07f-1c82-41c2-8422-5a1f117ff14d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
