<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_search</name>
   <tag></tag>
   <elementGuidId>b21616e5-ffa3-423f-83e2-858841eb425c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-container']/content/ng-component/div/mat-drawer-container/mat-drawer-content/div/div/app-payrun-remittances-list-mobile/div/div[2]/button/span/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-icon-button.mat-button-base.cdk-focused.cdk-touch-focused > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.button-class-text.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>b686c649-e378-49c3-bfc6-4d6f21c3815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b051946d-a64e-4b09-a35a-8c5ea3631d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate button-class-text material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>62d5c589-563e-471a-8c22-a1670f0dad65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e73b524-ce9e-46be-bef2-aec6202bde71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>2d3dc5ab-c89d-47de-b6b8-6aabbd37d5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>cad33659-4703-4b47-884e-a98b7951cdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/content[1]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[1]/mat-drawer-container[@class=&quot;mat-drawer-container drawer-form-container rebrand mat-drawer-container-explicit-backdrop&quot;]/mat-drawer-content[@class=&quot;mat-drawer-content&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-payrun-remittances-list-mobile[1]/div[1]/div[@class=&quot;icon-buttons&quot;]/button[@class=&quot;mat-focus-indicator mat-icon-button mat-button-base cdk-focused cdk-touch-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate button-class-text material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>da147629-2f8e-408e-8b11-03c37854d1af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-container']/content/ng-component/div/mat-drawer-container/mat-drawer-content/div/div/app-payrun-remittances-list-mobile/div/div[2]/button/span/mat-icon</value>
      <webElementGuid>3071e7c7-d731-4f1e-91cb-42929cec3ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload remittance'])[1]/following::mat-icon[2]</value>
      <webElementGuid>e3a7352d-8f90-4606-ba0f-d2bc57502366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indigo Group'])[1]/following::mat-icon[4]</value>
      <webElementGuid>ec152334-dcf5-4362-9bfd-dfebdd8e8b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Created'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>64bc25b7-0b17-4025-bf84-b49597b28e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference'])[1]/preceding::mat-icon[3]</value>
      <webElementGuid>c133fdb0-7550-49c1-93e1-26301dbad4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='search']/parent::*</value>
      <webElementGuid>d9579f7e-5bd7-469e-9b49-96cb8d668c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span/mat-icon</value>
      <webElementGuid>42a976aa-d6c0-47fa-bf58-251fb03b8db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>43cff263-6bf0-4e60-b808-87367f13ec5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-dialog[@id='invite-registered-company-dialog']/div/div/div[2]/div/mat-form-field/div/div/div/span/mat-icon</value>
      <webElementGuid>b3d99521-9643-4d60-b7cc-1097ce6ffb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Companies House'])[1]/following::mat-icon[2]</value>
      <webElementGuid>48fa42d0-2165-4db0-ab53-5ec5624f8c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not sure of the company number?'])[1]/following::mat-icon[2]</value>
      <webElementGuid>04e5821e-1386-4b5f-a910-0155d8dd8c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the company number'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>4a4d5d2c-1b8c-4221-8c44-24ba02b01d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>a48ab3bf-b495-47a3-8a57-6091d00bd0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field/div/div/div/span/mat-icon</value>
      <webElementGuid>a5cfa19e-c1ff-4c38-811f-95201c0580d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
