<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_receipt</name>
   <tag></tag>
   <elementGuidId>315c4961-5119-4c00-87e4-97a71ca13823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-elevation-z.primary.rebrand.mat-fab.mat-button-base.mat-accent.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.material-icons-outlined.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-drawer-open-button[@id='Btn_MyIndigo_Payruns_UploadNewRemittance']/a/button/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>d92ebe8c-fbd5-41ec-9cab-c1df9971750c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f0b3563-07fd-4459-948e-61109ee268da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons-outlined material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>c3d05fde-280e-4f6a-a31a-fd12c1ba372c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7ba372e-d412-4f34-a2a2-1526daa3e207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>b12f0df7-a419-4438-bf4c-57cc532bb516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>receipt</value>
      <webElementGuid>14e99cbe-57a1-4d5f-a496-8011729b862e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Btn_MyIndigo_Payruns_UploadNewRemittance&quot;)/a[@class=&quot;referrer-button&quot;]/button[@class=&quot;mat-focus-indicator mat-elevation-z primary rebrand mat-fab mat-button-base mat-accent cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons-outlined material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>f0eeb7b7-e966-43f1-b92f-516c982496ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-drawer-open-button[@id='Btn_MyIndigo_Payruns_UploadNewRemittance']/a/button/span/mat-icon</value>
      <webElementGuid>8c31f3de-8269-4c23-a643-49823a11b42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload New Remittance'])[1]/following::mat-icon[1]</value>
      <webElementGuid>2e992436-88bc-4e5f-b9e1-ea7f6fd4eb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/following::mat-icon[2]</value>
      <webElementGuid>8b971c9f-8aa9-41b5-a72b-4765afc1d530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/span/mat-icon</value>
      <webElementGuid>4673e11d-d3eb-428b-a575-eacc106c90cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'receipt' or . = 'receipt')]</value>
      <webElementGuid>c846e9d9-9856-44f8-8575-3b71c0b01097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
