<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_expand_more</name>
   <tag></tag>
   <elementGuidId>5f6bb9a5-bb4a-49da-b3ff-b752f298a71b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topNav']/div[3]/div/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.selected-organisation.brand-text.ng-star-inserted > mat-icon.mat-icon.notranslate.button-class-text.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>b3ff22e0-0d72-461b-a7cd-5ce1047025ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>006810cb-e698-45ae-8281-b59fa452eebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate button-class-text material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>1e53cceb-5df5-4eb1-88bc-7e89d358af12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1ea371b-69fc-4a6e-abc0-f54b8323f6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>b76eacd8-148a-4353-a86f-a82fe9c97b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>expand_more</value>
      <webElementGuid>43f748cb-69fd-43a9-8342-e0451099a09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topNav&quot;)/div[@class=&quot;organisation-selector&quot;]/div[@class=&quot;selected-organisation brand-text ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate button-class-text material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>a4ee277c-e933-4949-b338-34318cbfcb63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topNav']/div[3]/div/mat-icon</value>
      <webElementGuid>8b4054f7-a1bc-40a3-946a-374a1ea7726c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£ test 06831370 212123133.'])[1]/following::mat-icon[1]</value>
      <webElementGuid>6380a6ed-95a7-4f3c-8da4-bcbf9fdf44e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Hub'])[1]/following::mat-icon[1]</value>
      <webElementGuid>fe6deb48-964b-4fa7-82b0-3445b6fce9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Module'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>210f5519-bcc1-467b-ad98-acd068c51e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marquee Client Portal'])[2]/preceding::mat-icon[2]</value>
      <webElementGuid>a2f25cc8-aa2e-4cda-8439-c648b5da063d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='expand_more']/parent::*</value>
      <webElementGuid>c38b5b0c-eff2-4880-88db-c23e27a21655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-icon</value>
      <webElementGuid>fd593b02-b5ac-45b2-b76a-a420971fceb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'expand_more' or . = 'expand_more')]</value>
      <webElementGuid>b95d467a-0018-40f2-af09-229268c724cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>74aed4cb-58c5-4188-b1ab-588df76541f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
