<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_expand_more</name>
   <tag></tag>
   <elementGuidId>5f6bb9a5-bb4a-49da-b3ff-b752f298a71b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topNav']/div[3]/div/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.selected-organisation.brand-text.ng-star-inserted > mat-icon.mat-icon.notranslate.button-class-text.material-icons.mat-ligature-font.mat-icon-no-color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>1b26e8d0-a880-4c25-bc2a-cfcd11ce69b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>257ec363-5b9e-45da-91e3-18f1e2df696c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate button-class-text material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>5709ff80-b01e-4075-9694-58281cdd24e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3780db31-fccc-40b3-83e4-421d3e372dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>dae3f71b-418c-4c62-85a6-a583cea016de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>expand_more</value>
      <webElementGuid>0437142b-61a6-4c59-9208-191217419717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerColour&quot;)/div[2]/div[@class=&quot;content&quot;]/app-homepage-header[1]/div[@id=&quot;topNav&quot;]/div[@class=&quot;organisation-selector&quot;]/div[@class=&quot;selected-organisation brand-text ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate button-class-text material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>296d9d4e-db2b-4d99-bae6-92e541171765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topNav']/div[3]/div/mat-icon</value>
      <webElementGuid>23d7abc4-a491-41f1-90c6-34424a16c503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£ test 06831370 212123133.'])[1]/following::mat-icon[1]</value>
      <webElementGuid>aa7ef58b-9e12-4a4c-8ae9-45f45776f57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Hub'])[1]/following::mat-icon[1]</value>
      <webElementGuid>2c89b0a5-0e23-42cd-a75b-210a72543ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>74aed4cb-58c5-4188-b1ab-588df76541f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Module'])[2]/preceding::mat-icon[1]</value>
      <webElementGuid>61ba472f-d631-4065-8eed-b6eea97af2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='expand_more']/parent::*</value>
      <webElementGuid>42544c42-a285-4292-9232-7675567c98e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/mat-icon</value>
      <webElementGuid>ace3545b-9706-4616-bd9a-cdbf676c0d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'expand_more' or . = 'expand_more')]</value>
      <webElementGuid>e190351f-1743-4c86-8526-32409c6d4a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
