<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-tooltip-component_Phoebe Test Badge</name>
   <tag></tag>
   <elementGuidId>cc1070dd-35d2-41df-b71e-ea5c5e28444d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Phoebe Test Badge' or . = 'Phoebe Test Badge')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/mat-tooltip-component</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-tooltip-component.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-tooltip-component</value>
      <webElementGuid>2c69bf7b-91af-4f6e-9990-1d6140779310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7893e380-54b4-4f72-a72f-8034d015b912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>76a446f7-614b-4c92-8eda-7162c46ab378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phoebe Test Badge</value>
      <webElementGuid>227a84c7-0cf4-41f9-94e7-3dccc803ab0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)/mat-tooltip-component[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>b73e786e-34bc-4bc3-ade7-9ad6b03cec9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/mat-tooltip-component</value>
      <webElementGuid>6a4a31b8-cd85-4969-af19-0926d17de895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a test badge description'])[3]/following::mat-tooltip-component[1]</value>
      <webElementGuid>319454f6-f1c6-444d-af6d-78c648580a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phoebe Test Badge'])[3]/following::mat-tooltip-component[1]</value>
      <webElementGuid>0074cb0e-d788-4a71-9b83-cd8aece1c8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tooltip-component</value>
      <webElementGuid>bfe2442e-9d6c-4840-9fb4-239ae1c48faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-tooltip-component[(text() = 'Phoebe Test Badge' or . = 'Phoebe Test Badge')]</value>
      <webElementGuid>deddcf21-fcd3-4235-b90b-4ef1cdc142c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
