<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test 06831370 212123133</name>
   <tag></tag>
   <elementGuidId>59bdd8fc-b624-4614-9a1b-dcddc8afd34e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.selected-organisation-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topNav']/div[3]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>279cae0b-97bb-4c01-8bbb-10bd387e2419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-organisation-name</value>
      <webElementGuid>aa5f58db-fb77-42f5-9202-e6ee8189700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£ test 06831370 212123133.</value>
      <webElementGuid>914d06dc-aea2-4e51-9ccb-d178f20e608a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topNav&quot;)/div[@class=&quot;organisation-selector&quot;]/div[@class=&quot;selected-organisation brand-text ng-star-inserted&quot;]/span[@class=&quot;selected-organisation-name&quot;]</value>
      <webElementGuid>53350154-3d0e-44dd-a73d-9921b9ddfb76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topNav']/div[3]/div/span</value>
      <webElementGuid>8c6e3668-e7dd-4e25-94b9-c9c6a314fa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Hub'])[1]/following::span[1]</value>
      <webElementGuid>e1c75c9e-14ed-4402-9731-1ca3cb879917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Manager'])[1]/following::span[1]</value>
      <webElementGuid>d0a5240e-25a5-4280-be3c-449959a3f40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/preceding::span[1]</value>
      <webElementGuid>f4072cc6-3eae-4049-8509-b59db08b42bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Module'])[2]/preceding::span[1]</value>
      <webElementGuid>a243375e-5cb9-4465-9ec2-72f9d50199a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£ test 06831370 212123133.']/parent::*</value>
      <webElementGuid>69bd0ca0-832a-4529-8aa0-80d59bec969a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>0fec0fd0-1b08-4eeb-8ab7-2e29f7041f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '£ test 06831370 212123133.' or . = '£ test 06831370 212123133.')]</value>
      <webElementGuid>8961f091-428f-4c8e-95b8-06b5c8915a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
