<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Send Reset Link</name>
   <tag></tag>
   <elementGuidId>1aee1ddc-c862-4bcf-ba10-eb8d7226ba79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-forgot-password-send-link > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-forgot-password-send-link']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>303a0eea-0db9-4128-af47-0d0d4df88ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>dad4fa23-1e39-4a20-a8cd-c7cda1d37098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Send Reset Link </value>
      <webElementGuid>5ec026fc-7ff0-41d6-b997-a41937b31bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-forgot-password-send-link&quot;)/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>03bcac6e-be98-4a34-8948-0e258bd0a971</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-forgot-password-send-link']/span</value>
      <webElementGuid>63340a05-1ddf-45ae-bb43-daaec6e84d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to login'])[1]/following::span[1]</value>
      <webElementGuid>52b4c149-4ab6-4c94-a8df-106bd640a6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[2]</value>
      <webElementGuid>83d47f5b-6901-47b4-964f-7b40a75c4a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send Reset Link']/parent::*</value>
      <webElementGuid>ac85597c-439b-4f75-8c3c-0f23092986fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>fd9d9b6b-0c4c-490d-8a43-c5b6f5193c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Send Reset Link ' or . = ' Send Reset Link ')]</value>
      <webElementGuid>5bb0125f-ab20-4f94-bcde-18f7731dff78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
