<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Insurance</name>
   <tag></tag>
   <elementGuidId>78d12346-83d4-4622-8480-2f1747d9215b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-1268']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-1268 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6f39d20-bc72-4d28-999c-dc9edb4e1eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>68166701-6f34-4252-b555-298679493e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Insurance  </value>
      <webElementGuid>88f43279-1b9e-4a0d-9913-81533a347a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-1268&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>a4831519-1821-4ab4-a4e9-da72b5ca368b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-1268']/span</value>
      <webElementGuid>dd5fa5ee-fe51-474e-ac2b-4714122035fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indigo Services Europe - CIS Limited Companies'])[2]/following::span[1]</value>
      <webElementGuid>34027253-c7cc-4580-9e15-5c6e24197104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indigo - Automation Test Account'])[1]/following::span[2]</value>
      <webElementGuid>04061b00-8dc5-4978-95cc-a87660cd3050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISE Contractor June 2021'])[2]/preceding::span[1]</value>
      <webElementGuid>f1d00066-e32f-436e-a379-b38591229110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISS - CIS (Individuals) (1*)'])[35]/preceding::span[2]</value>
      <webElementGuid>8d7bf522-d100-40c7-b383-d8203b9af56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>14868fae-bc14-4dfc-9614-6dba86e9bf9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Insurance  ' or . = ' Insurance  ')]</value>
      <webElementGuid>c3e70d0b-9d58-41fb-8ca7-2bbaaf198a4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
