<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Invite</name>
   <tag></tag>
   <elementGuidId>978b47e1-29dd-4cb6-b82e-be0a645068f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-dialog[@id='invite-new-organisation-user-dialog']/div/div[2]/div/button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.primary.mat-raised-button.mat-button-base.cdk-focused.cdk-mouse-focused > span.mat-button-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd5c4181-b158-43e4-8651-328441039180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>b5194640-abd8-4b17-a5ed-036407033c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite</value>
      <webElementGuid>63ec1104-1912-4c41-acf8-b9090fe4a84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invite-new-organisation-user-dialog&quot;)/div[@class=&quot;dialog-container&quot;]/div[@class=&quot;mat-dialog-actions ng-star-inserted&quot;]/div[1]/button[@class=&quot;mat-focus-indicator primary mat-raised-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>d0b0585e-928d-41d2-a50b-be0189f33020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-dialog[@id='invite-new-organisation-user-dialog']/div/div[2]/div/button[2]/span</value>
      <webElementGuid>6ee28833-52c2-4099-8a06-d443d6a0a665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::span[3]</value>
      <webElementGuid>fe79099d-515b-4e51-872c-7ed8495116a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invite']/parent::*</value>
      <webElementGuid>91396556-9a19-44f4-9888-5363f6fcdefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dialog/div/div[2]/div/button[2]/span</value>
      <webElementGuid>51f3d71a-8ef0-41f2-a193-cd0880ecb7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Invite' or . = 'Invite')]</value>
      <webElementGuid>9b348ece-e722-432c-8bc1-cedadb9a1e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-dialog[@id='invite-new-individual-dialog']/div/div[2]/div/button[2]/span</value>
      <webElementGuid>eaaa1437-2d6d-40df-9042-1138bef60704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
