<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>f5bc90e5-6188-4680-91cb-0dab36ca71c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgotPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgotPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f8667032-3725-4e8b-9383-22feef5e1ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotPassword</value>
      <webElementGuid>e087bfed-4b2c-41fb-ba79-6cc0487f9ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=RWJlc3VkS0g5MHlpa2Zja0JSOTBpYkR6QWVTT3VQbGsvTWhHUHdCRnFYVGNzZHVibXBaWmdYbXBvYzVwTE5kTTgxTThKRjlERTNzeFdRVWs4bEJtQ0E9PTsyMDIzLTEwLTA0VDEzOjQ1OjE5LjI1NDIyNzFaO2IvTTg3L2d1QXdHSDlmVnpKL21RREE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiJmOWM4YjQyMC02MDY0LTRiOGYtYTc0NS1lOTAzM2YwZWZhYTkifQ&amp;p=B2C_1A_Driver_SignUpSignIn</value>
      <webElementGuid>0b975c76-5392-48ea-ad51-0de95d22b987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>0658e7d2-3998-46eb-af01-4c73628681ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPassword&quot;)</value>
      <webElementGuid>d70ff1c4-cf66-41e3-a262-828f534476db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgotPassword']</value>
      <webElementGuid>f88524c1-00ac-49d5-833d-e47ecf92cd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div[2]/div/a</value>
      <webElementGuid>48221551-cd9a-47bf-be76-6698017917a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>9625bda0-9df8-491e-a4d7-b0b1713b0550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>155a4346-e5b3-4e0b-bb2f-733412bb5ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::a[1]</value>
      <webElementGuid>f75e0e67-93e9-437d-b897-7f8f3d1a323b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>22408028-fb98-40f4-a9bf-c176d32c3474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>5e36f561-84b3-45a7-a47f-3bf7862a3aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=RWJlc3VkS0g5MHlpa2Zja0JSOTBpYkR6QWVTT3VQbGsvTWhHUHdCRnFYVGNzZHVibXBaWmdYbXBvYzVwTE5kTTgxTThKRjlERTNzeFdRVWs4bEJtQ0E9PTsyMDIzLTEwLTA0VDEzOjQ1OjE5LjI1NDIyNzFaO2IvTTg3L2d1QXdHSDlmVnpKL21RREE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiJmOWM4YjQyMC02MDY0LTRiOGYtYTc0NS1lOTAzM2YwZWZhYTkifQ&amp;p=B2C_1A_Driver_SignUpSignIn')]</value>
      <webElementGuid>5b0f8c4e-869e-4893-8f2d-00de0f881ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>cc7bd36e-692d-48ca-baf6-4a6227aa332b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgotPassword' and @href = '/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=RWJlc3VkS0g5MHlpa2Zja0JSOTBpYkR6QWVTT3VQbGsvTWhHUHdCRnFYVGNzZHVibXBaWmdYbXBvYzVwTE5kTTgxTThKRjlERTNzeFdRVWs4bEJtQ0E9PTsyMDIzLTEwLTA0VDEzOjQ1OjE5LjI1NDIyNzFaO2IvTTg3L2d1QXdHSDlmVnpKL21RREE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiJmOWM4YjQyMC02MDY0LTRiOGYtYTc0NS1lOTAzM2YwZWZhYTkifQ&amp;p=B2C_1A_Driver_SignUpSignIn' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>117dde50-d319-4118-a19e-075d43f6cee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
