<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>f5bc90e5-6188-4680-91cb-0dab36ca71c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgotPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgotPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e45f9acc-b197-4c8a-b857-a3ebd63797b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotPassword</value>
      <webElementGuid>ed2f1524-fb93-44c3-ae04-f7e47e484756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=THBaZE9ZWUVWSXVmeit6TExXejJ3RENYemZpOStVVGx0V1I5L2J4NlpMdmdWWEkrMkVGSDFwdkhPMEticy9tbVFmMzd4REYvK0o0RXlZZDcrSlEramc9PTsyMDIzLTEwLTA0VDEzOjU0OjQ4Ljk0OTIyMzhaO0owRDhkczJWMmNOdU5Ya1UvNW1haFE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiI5OWU2MTI0MS00Y2JhLTQxMmItYmE2Yy1iOTI1MWYxYWQyNTUifQ&amp;p=B2C_1A_Driver_SignUpSignIn</value>
      <webElementGuid>bd8d1af2-0973-4eb2-82bf-5cc91604bbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>3aae1705-b018-4659-993e-315cc2d7d586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPassword&quot;)</value>
      <webElementGuid>607e2733-21d6-4ec2-932d-639c8ec62a10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgotPassword']</value>
      <webElementGuid>910852d5-8c9e-41b7-b9e4-a3c1d8a1f75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div[2]/div/a</value>
      <webElementGuid>cf3159ff-c36f-4ba3-ac94-72b60d0436e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>931c2772-2ffb-4733-b2d7-e135e8598d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>2b37a2f8-0b47-4101-acd3-443c13d968d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::a[1]</value>
      <webElementGuid>ac972f31-646f-4289-9e3a-b61f3a5c80e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>8d62b3c1-1ecb-4334-b110-58a17cf5c717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>7747067e-ef18-4225-bf41-30d163026ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=THBaZE9ZWUVWSXVmeit6TExXejJ3RENYemZpOStVVGx0V1I5L2J4NlpMdmdWWEkrMkVGSDFwdkhPMEticy9tbVFmMzd4REYvK0o0RXlZZDcrSlEramc9PTsyMDIzLTEwLTA0VDEzOjU0OjQ4Ljk0OTIyMzhaO0owRDhkczJWMmNOdU5Ya1UvNW1haFE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiI5OWU2MTI0MS00Y2JhLTQxMmItYmE2Yy1iOTI1MWYxYWQyNTUifQ&amp;p=B2C_1A_Driver_SignUpSignIn')]</value>
      <webElementGuid>2c32cd90-7d43-4a31-a068-80223da10b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e26e4cfc-2405-4f8c-ad46-714ecc74f6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgotPassword' and @href = '/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=THBaZE9ZWUVWSXVmeit6TExXejJ3RENYemZpOStVVGx0V1I5L2J4NlpMdmdWWEkrMkVGSDFwdkhPMEticy9tbVFmMzd4REYvK0o0RXlZZDcrSlEramc9PTsyMDIzLTEwLTA0VDEzOjU0OjQ4Ljk0OTIyMzhaO0owRDhkczJWMmNOdU5Ya1UvNW1haFE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiI5OWU2MTI0MS00Y2JhLTQxMmItYmE2Yy1iOTI1MWYxYWQyNTUifQ&amp;p=B2C_1A_Driver_SignUpSignIn' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>eba9bb44-db9a-4e44-b1b5-ca4e0cfebd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=RWJlc3VkS0g5MHlpa2Zja0JSOTBpYkR6QWVTT3VQbGsvTWhHUHdCRnFYVGNzZHVibXBaWmdYbXBvYzVwTE5kTTgxTThKRjlERTNzeFdRVWs4bEJtQ0E9PTsyMDIzLTEwLTA0VDEzOjQ1OjE5LjI1NDIyNzFaO2IvTTg3L2d1QXdHSDlmVnpKL21RREE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiJmOWM4YjQyMC02MDY0LTRiOGYtYTc0NS1lOTAzM2YwZWZhYTkifQ&amp;p=B2C_1A_Driver_SignUpSignIn')]</value>
      <webElementGuid>5b0f8c4e-869e-4893-8f2d-00de0f881ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgotPassword' and @href = '/gatsbytest.onmicrosoft.com/B2C_1A_Driver_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=RWJlc3VkS0g5MHlpa2Zja0JSOTBpYkR6QWVTT3VQbGsvTWhHUHdCRnFYVGNzZHVibXBaWmdYbXBvYzVwTE5kTTgxTThKRjlERTNzeFdRVWs4bEJtQ0E9PTsyMDIzLTEwLTA0VDEzOjQ1OjE5LjI1NDIyNzFaO2IvTTg3L2d1QXdHSDlmVnpKL21RREE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjozfQ==&amp;tx=StateProperties=eyJUSUQiOiJmOWM4YjQyMC02MDY0LTRiOGYtYTc0NS1lOTAzM2YwZWZhYTkifQ&amp;p=B2C_1A_Driver_SignUpSignIn' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>117dde50-d319-4118-a19e-075d43f6cee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
