<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_givenName</name>
   <tag></tag>
   <elementGuidId>06598a5a-c6ba-48b1-983c-c56bb2323997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='givenName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#givenName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6af71c58-4798-400b-9aee-027fbb51b1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>givenName</value>
      <webElementGuid>a9b1e44b-2cbb-4359-9bc8-94239ddb9b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>c1d95803-38c2-4463-bb97-8fa2ae220629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71220c3c-fd58-4982-924b-7fe09035514c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>7bae517a-d5ed-460b-b1c1-efeea03cb2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>c91604a0-a86e-466a-afa5-b00e7a309dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Your given name (also known as first name).</value>
      <webElementGuid>df3c2bae-ff0d-43b2-ba49-c5eac9b0891f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>afc1caea-e2e1-4962-b9dc-731f881bb579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>d3ef4f46-fef7-4f85-941d-223929fbd47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;givenName&quot;)</value>
      <webElementGuid>9cd56d9b-df0b-4d71-8f15-4212df6c0c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='givenName']</value>
      <webElementGuid>a0449d25-53c4-47d2-803a-851d983c2b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attributeList']/ul/li/div/input</value>
      <webElementGuid>d5c2a19e-a339-4fa5-b379-1bb92c08b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>88618fe8-83ec-4fb1-9bd9-5849840b3b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'givenName' and @type = 'text' and @placeholder = 'First name' and @title = 'Your given name (also known as first name).']</value>
      <webElementGuid>8f579d7b-7d3c-4920-aa1c-de028d0da607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
