<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot your password</name>
   <tag></tag>
   <elementGuidId>637624fc-56d2-441c-bc8f-3d276663c981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#forgotPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='forgotPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>032433bc-499d-4e3d-b9af-01deb91456b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forgotPassword</value>
      <webElementGuid>b2f37e18-af09-4e32-a3e9-96afcb50d9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gatsbytest.onmicrosoft.com/B2C_1A_Operator_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=anFubllPYklTdVV0SWRBQXJkb1BIN0N6ZDRmMDgzaXBOWWVpeE9haUdnNW1jc1RsMko0WFpHbE83dE4yS2tDdGhKaUFONWNVckdwNGx0Sm83SXFoK2c9PTsyMDIzLTEwLTA0VDEzOjQzOjE3LjgwMTEzMTJaO0lTYm0zaEVpekNrTGE5VkJmVDM0blE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjo0fQ==&amp;tx=StateProperties=eyJUSUQiOiI3YmZmMGY2OS0yYWJiLTQzYjItOTM3Yy1lM2MzNTQ5NDdmMDMifQ&amp;p=B2C_1A_Operator_SignUpSignIn</value>
      <webElementGuid>b13f6023-5ed9-4402-a0f2-8fc2e880abe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot your password?</value>
      <webElementGuid>433b0aed-b554-4f76-9af3-b50d5978d535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forgotPassword&quot;)</value>
      <webElementGuid>399e7d41-8c6b-42f8-8ef9-51f59908a68d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='forgotPassword']</value>
      <webElementGuid>c8ba1015-6616-41c0-a058-44232af40b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='localAccountForm']/div[3]/div[2]/div/a</value>
      <webElementGuid>b23c58a9-d590-4fff-8784-a418e7f1d018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot your password?')]</value>
      <webElementGuid>77704c4e-6fc2-4b31-8eb4-11b1f5746443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[1]</value>
      <webElementGuid>45669234-ba53-4b10-b10b-fbe64be3a03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::a[1]</value>
      <webElementGuid>caf3cca2-010e-4fd6-b9eb-bc9f74c915ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::a[1]</value>
      <webElementGuid>75fa20cb-be7b-4b0e-a77a-c1c426c08315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot your password?']/parent::*</value>
      <webElementGuid>b237c7d3-16c4-4ca1-b4d8-8570ca65cc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gatsbytest.onmicrosoft.com/B2C_1A_Operator_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=anFubllPYklTdVV0SWRBQXJkb1BIN0N6ZDRmMDgzaXBOWWVpeE9haUdnNW1jc1RsMko0WFpHbE83dE4yS2tDdGhKaUFONWNVckdwNGx0Sm83SXFoK2c9PTsyMDIzLTEwLTA0VDEzOjQzOjE3LjgwMTEzMTJaO0lTYm0zaEVpekNrTGE5VkJmVDM0blE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjo0fQ==&amp;tx=StateProperties=eyJUSUQiOiI3YmZmMGY2OS0yYWJiLTQzYjItOTM3Yy1lM2MzNTQ5NDdmMDMifQ&amp;p=B2C_1A_Operator_SignUpSignIn')]</value>
      <webElementGuid>5c5c6cad-9bb4-4ec6-ab49-74e0e6381fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6a482904-e48a-4d58-8c04-9e61a7d9ce08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'forgotPassword' and @href = '/gatsbytest.onmicrosoft.com/B2C_1A_Operator_SignUpSignIn/api/CombinedSigninAndSignup/unified?claimsexchange=ForgotPasswordExchange&amp;csrf_token=anFubllPYklTdVV0SWRBQXJkb1BIN0N6ZDRmMDgzaXBOWWVpeE9haUdnNW1jc1RsMko0WFpHbE83dE4yS2tDdGhKaUFONWNVckdwNGx0Sm83SXFoK2c9PTsyMDIzLTEwLTA0VDEzOjQzOjE3LjgwMTEzMTJaO0lTYm0zaEVpekNrTGE5VkJmVDM0blE9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjo0fQ==&amp;tx=StateProperties=eyJUSUQiOiI3YmZmMGY2OS0yYWJiLTQzYjItOTM3Yy1lM2MzNTQ5NDdmMDMifQ&amp;p=B2C_1A_Operator_SignUpSignIn' and (text() = 'Forgot your password?' or . = 'Forgot your password?')]</value>
      <webElementGuid>cae2d579-f976-4e75-ab58-d1765e35527b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
