<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send verification code</name>
   <tag></tag>
   <elementGuidId>729bb9d6-11a1-4995-a731-6b9b77d9d59d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_ver_but_send</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='email_ver_but_send']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06f6bacd-1b1d-4e37-81b7-4fb91dabf039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendButton</value>
      <webElementGuid>a8cc2861-d2ed-476b-8e5f-6f725ca6ca24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_ver_but_send</value>
      <webElementGuid>547a5f02-cab3-4edf-bd4a-7d0d1a2b00bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fea26533-0886-47d3-b1c6-e38e0fad768b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Send verification code</value>
      <webElementGuid>8cd004be-756f-4247-a869-6d1bbae04728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1611c9d3-e859-4cda-8f31-1ae39b6020b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send verification code</value>
      <webElementGuid>07b882b1-e0df-47d0-b46f-85bdff0d17c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_ver_but_send&quot;)</value>
      <webElementGuid>6e6dc2bd-e400-4495-9136-83834af88559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='email_ver_but_send']</value>
      <webElementGuid>c6098551-e988-433d-baad-a4585c48b25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attributeList']/ul/li/div/div[3]/button</value>
      <webElementGuid>5d2d589b-88bd-4469-881e-57ec8bf88520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is this?'])[1]/following::button[1]</value>
      <webElementGuid>d2af1f5c-ab3b-4318-92d7-fb3879854f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::button[1]</value>
      <webElementGuid>d919c645-5128-407e-a59d-253bda1c0617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/preceding::button[4]</value>
      <webElementGuid>cf949374-145e-4377-9055-f05c0382ae64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[5]</value>
      <webElementGuid>34eef92c-e080-42c6-9977-af93b65f1259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send verification code']/parent::*</value>
      <webElementGuid>5cf42c69-4075-48a8-ae03-119ae5c20acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2d0fafb9-3652-40e3-9563-07bac4baf22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'email_ver_but_send' and @type = 'button' and (text() = 'Send verification code' or . = 'Send verification code')]</value>
      <webElementGuid>42d23747-a98e-48a7-bf96-5b298a482728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
